version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    hostname: my-selenoid
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/selenoid:/etc/selenoid/" # assumed current dir contains browsers.json
      - "$PWD/selenoid/video:/opt/selenoid/video"
      - "$PWD/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "jenkins"]
    networks:
      jenkins: null

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: jenkins/jenkins:2.426.1-jdk17
    container_name: jenkins
    restart: on-failure:3
    volumes:
      - "jenkins-data:/var/jenkins_home"
    ports:
      - "8085:8080"
    networks:
      jenkins: null

  mariadb:
    image: bitnami/mariadb:11.0
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      jenkins: null
  
  opencart:
    image: bitnami/opencart:3
    container_name: opencart
    hostname: my-opencart
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=my-opencart:8080
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      jenkins: null

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
  jenkins-data:
    driver: local

networks:
  jenkins:
    external: true
